import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const server={name:'WolfROYALE',members:718,online:52,roles:46,channels:74,emojis:126,boosts:30,level:3,messages:85};
const roleData=[['Mainframe',38,0,'bot'],['</>',37,1,'bot'],['Sync',36,0,'bot'],['Statistics',35,0,'bot'],['<LGTR>',34,0,'red'],['🌊',33,3,'blue'],['♜ Owner',32,2,'white']];
const channelData=[
 {cat:'BİLGİLENDİRME',count:'6/6',items:[['🇹🇷','18810019...','Text'],['📚','Kurallar','Text'],['📣','Duyurular','Text'],['🌞','Booster-...','Text'],['📥','Gelen-Gi...','Text'],['📱','S-S','Text']]},
 {cat:'YÖNETİM ODALARI',count:'8/8',items:[['🌎',"God's Meeti...",'Ses'],['⚠️','Yetkili-D...','Text'],['📡','Meeting','Ses'],['📱','Yetkili-K...','Text'],['🪵','Yetkili-U...','Text'],['🏆','İZİNSİZ GİRM...','Ses'],['💎','Yetkili...','Text'],['🔐','Yetkili-C...','Text']]}
];
const logs=[
 ['ERROR','guard-log','[30 Ağustos 2026 21:43] ERROR guard-log kanalını WolfROYALE sunucusunda aradım fakat bulamadım.'],
 ['INFO','system','[checkMember] darkpolis (474282366718705685) | type:undefined | botSelf:false owner:true unManageable:true BOTS:false staff:false'],
 ['INFO','system','[checkMember] BOTS: [1510281911128293507,1510281006588887280,1510281297447227413,15102811401061663322] unManageable: [4742822366718705685,843136836947410945]']
];
const protections=[['Webhook Koruması','Webhook işlemlerini engeller.',true],['Sunucu Koruması','Sunucu içerisinde yapılan izinsiz olan izinleri engeller.',true],['Tarayıcı(Web) Koruması','Tarayıcıya girene yetki çekme.',true],['Çevrim-Dışı Koruması','Çevrim-dışı olunca yetki çekilir.',true],['Emoji Koruması','Emoji işlemlerini engeller.',false],['Çıkartma Koruması','Sticker işlemlerini engeller.',false],['Üye Çıkartma Koruması','Üye çıkartma engelleme.',true],['Üye(Rol/Ver) Koruması','Rol ver/al engellemesi.',true],['Ban Koruması','Ban engellemesi.',true],['Susturma Koruması','Susturma engellemesi.',true],['Atma Koruması','Sunucudan atmayı engeller.',true]];
const nav=[['⌂','Ana Sayfa','home'],['⚙','Sunucu Ayarları','settings'],['♢','Koruma Sistemi','protection'],['♜','Roller','roles'],['#','Kanallar','channels'],['♙','Üyeler','members'],['☷','Görevler','tasks'],['▤','PM2 Logları','logs'],['⚙','Sistem','system']];
function App(){
 const [page,setPage]=useState('home'),[drawer,setDrawer]=useState(false),[toast,setToast]=useState(''),[vals,setVals]=useState(Object.fromEntries(protections.map(x=>[x[0],x[2]]))),[search,setSearch]=useState('');
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),1600)};
 const toggle=k=>setVals(v=>({...v,[k]:!v[k]}));
 return <div className="app">
  <div className={'drawer '+(drawer?'show':'')}><div className="drawer-head"><b>WolfROYALE</b><button onClick={()=>setDrawer(false)}>×</button></div>{nav.map(([i,l,id])=><button className={page===id?'active':''} key={id} onClick={()=>{setPage(id);setDrawer(false)}}><span>{i}</span>{l}</button>)}<div className="drawer-foot"><span className="live-dot"/> Bot Çevrim içi</div></div>
  <main><header><button className="circle-btn menu" onClick={()=>setDrawer(true)}>☰</button><button className="server-pill"><span>W</span> WolfROYALE <b>⌄</b></button><div className="head-right"><button className="circle-btn">♧<i/></button><button className="avatar">D</button></div></header>
   <div className="page">{page==='home'&&<Home notify={notify}/>} {page==='protection'&&<Protection vals={vals} toggle={toggle}/>} {page==='roles'&&<Roles notify={notify} search={search} setSearch={setSearch}/>} {page==='channels'&&<Channels notify={notify}/>} {page==='members'&&<Members/>} {page==='tasks'&&<Tasks notify={notify}/>} {page==='logs'&&<Logs/>} {page==='settings'&&<Settings vals={vals} toggle={toggle}/>} {page==='system'&&<System notify={notify}/>}</div>
   <button className="orb" onClick={()=>notify('Hızlı işlemler')}>⌘</button>
  </main>{toast&&<div className="toast">{toast}</div>}
 </div>
}
function Top({text,action,onAction}){return <div className="topline"><span><i className="live-dot"/> {text}</span>{action&&<button className="light-btn" onClick={onAction}>{action}</button>}</div>}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Home({notify}){return <><Top text="WolfROYALE" action="⟳ Yenile" onAction={()=>notify('Yenilendi')}/><Card className="hero"><img src="/wolfroyale.png"/><div><h1>WolfROYALE</h1><p>Açıklama bulunamadı.</p><div className="hero-stats"><span>♧ 718 üye</span><span>♢ 46 rol</span><span># 74 kanal</span><span>✧ 126 emoji</span><span>♕ Lvl 3 · 30 boost</span></div></div></Card><div className="stats-grid"><Metric title="ÜYELER" value="718" sub="↗ 2 kişi (24s)" icon="♙"/><Metric title="ONLINE" value="52" sub="— %7 aktif" icon="⌁"/><Metric title="SESTE" value="0" sub="— 0 yayında · 0 kamera" icon="♩"/><Metric title="MESAJLAR (TOPLAM)" value="85" sub="↗ 0 taglı üye" icon="□"/></div><Card className="activity-card"><div className="card-title"><b>BUGÜN (24S)</b><b>HAFTA</b></div><div className="activity-grid"><div><strong>9</strong><small>üye hareketi</small></div><div><strong>62</strong><small>mesaj</small></div><div><strong>240</strong><small>toplam işlem</small></div></div></Card></>}
function Metric({title,value,sub,icon}){return <Card className="metric"><div className="metric-head"><b>{title}</b><span>{icon}</span></div><strong>{value}</strong><small>{sub}</small></Card>}
function Toggle({on,onChange}){return <button className={'toggle '+(on?'on':'')} onClick={()=>onChange(!on)}><span/></button>}
function Protection({vals,toggle}){return <><Top text="Sunucu güvenlik koruması · 7/24 izle..." action="▣ Kaydet"/><Card className="master"><div className="shield">♢</div><div><small>ANA KORUMA</small><h1>Etkin <em>· 18/20 koruma aktif</em></h1><p>Tüm guard modüllerini açıp/kapatana anahtar.</p></div><Toggle on={Object.values(vals).filter(Boolean).length>0} onChange={()=>{}}/></Card><div className="searchbox">⌕ <input placeholder="Koruma ara... (örn. webhook, ban, url)"/></div><Card><div className="group-title"><span>♢</span><div><b>Diğer</b><small>4 öğe</small></div><em>2/2</em></div>{protections.slice(0,4).map(x=><SettingRow key={x[0]} item={x} on={vals[x[0]]} change={()=>toggle(x[0])}/>)}</Card><Card><div className="group-title"><span>♢</span><div><b>Koruma Limitleri</b><small>6 öğe</small></div></div>{[['Mute Atma Limiti','7'],['Ses Mute Atma Limiti','7'],['Jail Atma Limiti','5'],['Ban/Underworld Atma Limiti','3']].map(x=><InputRow key={x[0]} {...{title:x[0],value:x[1]}}/>)}</Card></>}
function SettingRow({item,on,change}){return <div className="setting-row"><div><h3>{item[0]}</h3><p>{item[1]}</p></div><Toggle on={on} onChange={change}/></div>}
function InputRow({title,value}){return <div className="input-row"><div><h3>{title}</h3><p>Belirlenen rakam kadar işlem yapıldığında otomatik engeller.</p></div><input defaultValue={value}/></div>}
function Settings({vals,toggle}){return <><Top text="Sunucu ayarları · yapılandırma" action="▣ Kaydet"/><Card><SettingRow item={['Otomatik AFK Odası Taşıma','10 dakika boyunca kulaklığı veya mikrofonu kapalı olan üyeleri otomatik AFK odasına taşır.',true]} on={true} change={()=>{}}/><SettingRow item={['Yapazeka Kayıt Sistemi','Sunucuya giren üyeler Yapazeka API üzerinden otomatik olarak kayıt edilir.',true]} on={true} change={()=>{}}/></Card><Card><h2>Roller ve Kanallar</h2>{['Booster Rolü','Toplantı (Katıldı) Rolü','Sorun Çözme Kategorisi','Sorun Çözücü Roller','Etkinlik Katılımcısı Rolü','Çekiliş Katılımcısı Rolü'].map(x=><div className="select-row" key={x}><div><h3>{x}</h3><p>Sunucudaki uygun seçeneği belirleyin.</p></div><button>+ Rol seç　⌄</button></div>)}</Card></>}
function Roles({notify,search,setSearch}){const [roles,setRoles]=useState(roleData);const shown=roles.filter(r=>r[0].toLowerCase().includes(search.toLowerCase()));return <><Top text="46 rol · toplam 718 atama · sürükle-bı..." action="＋ Yeni rol" onAction={()=>{setRoles(r=>[...r,['Yeni Rol',r.length,0,'white']]);notify('Yeni rol oluşturuldu')}}/><Card className="table-card"><div className="searchbox"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rol ara..."/></div><div className="table-head"><b>ROL</b><b>POS.</b><b>ÜYE</b></div>{shown.map(r=><div className="role-row" key={r[0]}><span className="drag">⁙</span><span className={'role-color '+r[3]}/><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span></div>)}</Card><Card className="role-edit"><div className="role-preview"><span className="role-big">♜</span><div><strong>Rol seçildi</strong><small>id: 1519017915914129420</small></div></div><div className="edit-actions"><button onClick={()=>notify('Rol düzenleme')}>☷ Düzenle</button><button className="danger" onClick={()=>notify('Silme işlemi onay bekliyor')}>♧ Sil</button></div></Card></>}
function Channels({notify}){return <><Top text="74 kanal · toplam 109 öğe" action="＋ Yeni kanal" onAction={()=>notify('Yeni kanal')}/><Card className="channels">{channelData.map(c=><div key={c.cat} className="channel-group"><div className="cat"><span>⌄　▱</span><b>✦ {c.cat}</b><small>{c.count}</small></div>{c.items.map((x,i)=><div className="channel-row" key={i}><span className={x[2]==='Ses'?'speaker':'hash'}>{x[2]==='Ses'?'♬':'#'}</span><strong>{x[0]} | {x[1]}</strong><em className={x[2]==='Ses'?'voice':'text'}>{x[2]}</em></div>)}</div>)}</Card></>}
function Members(){return <><Top text="718 üye · 52 çevrim içi" action="⟳ Yenile"/><Card>{['darkpolis','RoyaleUser','Görkem','Support','WolfAdmin','Guest'].map((x,i)=><div className="member" key={x}><span className="avatar small">{x[0].toUpperCase()}</span><div><strong>{x}</strong><small>{i%2?'Çevrimdışı':'Çevrim içi'}</small></div><em>{i%3?'Üye':'Yetkili'}</em></div>)}</Card></>}
function Tasks({notify}){const [open,setOpen]=useState(false);return <><Top text="Görevler · otomasyon" action="＋ Yeni Görev" onAction={()=>setOpen(true)}/><Card><div className="task-row"><div><h3>Guard görevleri</h3><p>Görev oluşturulduğunda roldeki üyelere DM atılır ve ilgili sayaçlar sıfırlanır.</p></div><span className="pill onpill">Aktif</span></div><div className="task-row"><div><h3>Haftalık sunucu özeti</h3><p>7 günde bir otomatik rapor.</p></div><span className="pill">7d</span></div></Card>{open&&<TaskModal close={()=>setOpen(false)} notify={notify}/>}</>}
function TaskModal({close,notify}){return <div className="modal"><div className="modal-box"><button className="modal-x" onClick={close}>×</button><h1>Yeni Görev</h1><label>HEDEF ROL</label><button className="select">● GUARD II　⌄</button><div className="two"><Field label="GENEL SES (SAAT)"/><Field label="AÇIK SES (SAAT)"/></div><div className="two"><Field label="TAGLI ÜYE"/><Field label="YETKİLİ İŞLEM"/></div><div className="two"><Field label="DAVET"/><Field label="KAYIT"/></div><div className="two"><Field label="SORUMLULUK"/><Field label="ÖDÜL (COIN)" value="50"/></div><label>SÜRE (ÖRN "7D", "1H", "UNLIMITED")</label><input defaultValue="7d"/><p>Görev oluşturulunca: rolde olan tüm üyelere DM atılır, görev-bilgi kanalına container post edilir, ilgili sayaçlar sıfırlanır.</p><div className="modal-actions"><button onClick={close}>İptal</button><button className="light-btn" onClick={()=>{notify('Görev oluşturuldu');close()}}>＋ Oluştur</button></div></div></div>}
function Field({label,value='0'}){return <div><label>{label}</label><input defaultValue={value}/></div>}
function Logs(){const [filter,setFilter]=useState('Tümü'),[q,setQ]=useState('');const shown=logs.filter(l=>(filter==='Tümü'||l[0]===filter.toUpperCase())&&l.join(' ').toLowerCase().includes(q.toLowerCase()));return <><Top text="1000 satır · canlı PM2 logları"/><Card className="logs"><div className="searchbox"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Logda ara..."/></div><div className="filters">{['Tümü','Info','Warn','Error'].map(f=><button className={filter===f?'selected':''} key={f} onClick={()=>setFilter(f)}>{f} <b>{f==='Tümü'?1000:f==='Info'?596:f==='Error'?404:0}</b></button>)}</div>{shown.map((l,i)=><div className={'log '+l[0].toLowerCase()} key={i}><span>{l[0]}</span><code>{l[1]}</code><p>{l[2]}</p></div>)}</Card><div className="log-foot">1000 satır gösteriliyor　·　<span className="live-dot"/> canlı　·　5s'de bir tazelenir</div></>}
function System({notify}){return <><Top text="Sistem durumu · servisler"/><div className="stats-grid"><Metric title="BOT" value="ONLINE" sub="Discord.js v14" icon="●"/><Metric title="PM2" value="RUNNING" sub="1 process" icon="Ⅱ"/><Metric title="MONGODB" value="READY" sub="Bağlantı hazır" icon="◇"/><Metric title="API" value="OK" sub="REST aktif" icon="⌁"/></div><Card><h2>Sistem Bağlantısı</h2><p>Panel → API → Discord bot → MongoDB bağlantısı.</p><button className="light-btn" onClick={()=>notify('Bağlantı testi başarılı')}>Bağlantıyı Test Et</button></Card></>}

createRoot(document.getElementById('root')).render(<App/>);
